### ISSUE TITLE
Safety with malicious code?

### ISSUE THREAD

**Issue by tmcw** [olark/lightningjs#1]
Hi,

Extremely interesting project, and sorry I don't have a ton of time to kick the tires to answer this question myself - I might later today - but as far as safety, the main goal is to provide safety in terms of conflicts, not as far as sandboxing or preventing malicious third-party code fromm taking effect? It would seem that the `window.parent` is still fully accessible and common attacks like framebusting, cookie stealing, etc., are possible? Not saying that preventing those attacks should be a goal of this project - it seems like it's near-impossible and possibly not worth the effort without a Google Caja-like parsing/regeneration system.

**Comment by mjpizz** [comment]
Thanks for the feedback Tom! That kind of safety is actually outside the scope of LightningJS.  Framebusting doesn't really apply in this case since we are only using an "anonymous" frame to gain a new `window` context (not firewall the code from the parent page), and cookies are always fully available to embedded third-party Javascript.

We have to assume that the end user trusts the code given to them by the third-party Javascript provider...after all, they're pasting it into their webpage.  The main benefit safety-wise is just avoiding code conflicts between different libraries :)
